data:
  cleaned_data: "data/cleaned_weather.csv"
  train_data: "data/train.csv"
  validation_data: "data/validation.csv"
  test_data: "data/test.csv"

model:
  parameters:
    - epochs: 50
      batch_size: 32

report:
  file_path: "detailed_report.csv"