data:
  cleaned_data: "data/cleaned_weather.csv"
  train_data: "data/train.csv"
  validation_data: "data/validation.csv"
  test_data: "data/test.csv"

model:
  parameters:
    - n_estimators: 100
      learning_rate: 0.1
      max_depth: 3

report:
  file_path: "detailed_report.csv"